### ISSUE TITLE
Merge patches from the old repository

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#3]
There's a bunch of patches attached to [the old repository tracker](https://bugs.launchpad.net/wpf-math). I think it should be worth to check them out and apply to our codebase.

- [x] [Feature: added color](https://bugs.launchpad.net/wpf-math/+bug/1052493)
- [x] [Rendering of accent symbols](https://bugs.launchpad.net/wpf-math/+bug/1033830)
- [x] [incorrect image size when using subscript](https://bugs.launchpad.net/wpf-math/+bug/1041219)
- [x] [Background isn't drawn when using a single char](https://bugs.launchpad.net/wpf-math/+bug/1046368)
- [x] [Image size: Italic support](https://bugs.launchpad.net/wpf-math/+bug/1046669)
- [x] [Incorrect XML serialization in different regions](https://bugs.launchpad.net/wpf-math/+bug/1050912)
- [x] [Feature: Render geometry & output as SVG](https://bugs.launchpad.net/wpf-math/+bug/1050955)
- [x] [Loading of predefined formulas](https://bugs.launchpad.net/wpf-math/+bug/1052586)
- [x] [Added whitespace and % rendering](https://bugs.launchpad.net/wpf-math/+bug/1052891)

Ideally we should treat these patches as our own pull requests: we should try our best to reproduce the mentioned issues (probably even write the unit tests), and merge the changes afterwards. The maintainer on duty (well, probably myself) should notify the patch authors that the patches are being merged here.

**Comment by ForNeVeR** [comment]
Thanks to @gsomix, we've merged all the patches. I've notified all the possibly interested parties about that.
